### PR TITLE
8193

### PR DESCRIPTION
**Pull request by FraGoTe**
Please before Merge this PR add the field room_id
<code>
alter table track_e_teacher_in_out add room_id int;
</code>
Modify cases name and add room_id field - refs BT#8193

### CODE REVIEW

**Comment by FraGoTe** [comment]
To execute the cron:

<pre>
php console.php chamilo:sendTeacherAttendance
</pre>

Before merge this please add this field

<pre>
alter table track_e_teacher_in_out add sync int;
</pre>

This field is going to help to know if there was a sync.

<pre>
  /**
   * 0 or NULL => Not sync
   * 1 => IN SYNC
   * 2 => OUT SYNC
   */
</pre>

**Comment by FraGoTe** [comment]
# A brief summary

Add just the following field
<code>
 alter table track_e_teacher_in_out add room_id int;
</code>

And while I was debugging the cron I realized that the first query to branch_transaction is very slow so I would recommend add the next indexes, it took me about 30 minutes but then I was very fast.
<code>
ALTER TABLE track_e_teacher_in_out
ADD INDEX idx_select (id, branch_id, status_id, action);
</code>

**Comment by ywarnier** [comment]
Are the sync, action and status_id fields still required? (since you are using branch_transaction now)

**Comment by FraGoTe** [comment]
Sync it is not used anymore. But It would be great to add the index those indexes to track_e_teacher_in_out

**Comment by ywarnier** [comment]
My track_e_teacher_in_out table looks like this, right now:
+---------------------+----------+------+-----+---------+----------------+
| Field               | Type     | Null | Key | Default | Extra          |
+---------------------+----------+------+-----+---------+----------------+
| id                  | int(11)  | NO   | PRI | NULL    | auto_increment |
| user_id             | int(11)  | NO   |     | NULL    |                |
| course_id           | int(11)  | NO   |     | NULL    |                |
| session_id          | int(11)  | YES  |     | NULL    |                |
| log_in_course_date  | datetime | YES  |     | NULL    |                |
| log_out_course_date | datetime | YES  |     | NULL    |                |
| room_id             | int(11)  | YES  |     | NULL    |                |
+---------------------+----------+------+-----+---------+----------------+

So I guess I should still add the status_id, branch_id and action, then?

**Comment by FraGoTe** [comment]
No, those indexes are to branch_transaction.

**Comment by ywarnier** [comment]
OK, so in fact it's:
ALTER TABLE branch_transaction ADD INDEX idx_select (id, branch_id, status_id, action);

**Comment by FraGoTe** [comment]
Yes, you're right

**Comment by ywarnier** [comment]
I'm going to need a re-merge here as well. It's also giving me some main/newscorm conflict stuff...

**Pull request merged**
